[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]  # list of folders that contain the packages (["."] by default)
include = ["vrag"]  # package names should match these glob patterns (["*"] by default)
exclude = []  # exclude packages matching these glob patterns (empty by default)
namespaces = false  # to disable scanning PEP 420 namespaces (true by default)

[project]
name = "vrag"
version = "0.0.1"
authors = [
  { name="Minkyu Choi", email="minkyu.choi@coargus.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "langchain",
    "langchain-upstage",
    "langchain_chroma",
    "langchain[google-vertexai]",
    "langchain-openai",
    "langchain-chroma",
    "requests",
    "langchain-text-splitters",
    "langchain-community",
    "langgraph",
    "google_cloud_aiplatform",
    "typing-extensions",
    "qdrant-client",
    "openai",
    "langchain-community",
    "beautifulsoup4"
]

[project.urls]
"Homepage" = "https://github.com/Coargus/template-python-package"
"Bug Tracker" = "https://github.com/Coargus/template-python-package/issues"

[project.optional-dependencies]
dev = ["black", "ruff", "mypy"]
test = ["pytest", "pytest-cov", "pytest-mock"]